config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comments, only: [:new, :create, :index]
  root to: 'comments#new'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true, length: {maximum: 2000}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :comments, dependent: :delete_all

	class << self
		def from_omniauth(auth)
			provider = auth.provider
			uid = auth.uid
			info = auth.info.symbolize_keys!
			user = User.find_or_initialize_by(uid: uid, provider: provider)
			user.name = info.name
			user.avatar_url = info.image
			user.profile_url = info.urls.send(provider.capitalize.to_sym)
			user.email = info.email
			user.save!(validate: false)
			user
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @comments = Comment.where('id > ?',params[:after_id].to_i).order('created_at DESC')
  end

  def new
  	@comment = Comment.new
  	@comments = Comment.order('created_at DESC')
  end

  def create
    respond_to do |format|
    	if current_user
    		@comment = current_user.comments.build(comment_params)
    		if @comment.save
    			flash[:success] = 'Your comment was successfully posted!'
    		else
    			flash[:error] = 'Your comment cannot be saved.'
    		end
        format.html {redirect_to root_url}
        format.js
      else
        format.html {redirect_to root_url}
        format.js {render nothing: true}
      end
  	end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:body)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(request.env['omniauth.auth'])
		session[:user_id] = user.id
		flash[:success] = "Hello, #{user.name}!"
		redirect_to root_url
	end

	def destroy
		session.delete(:user_id)
		flash[:success] = "See you"
		redirect_to root_url
	end

	def auth_fail
		render text: "Failure"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<li class="media comment" data-id="<%= comment.id %>">
  <%= link_to image_tag(comment.user.avatar_url, alt: comment.user.name, class: "media-object"),
              comment.user.profile_url, target: '_blank', class: 'pull-left' %>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to comment.user.name, comment.user.profile_url, target: '_blank' %> says
      <small class="text-muted">[at <%= comment.created_at.strftime('%-d %B %Y, %H:%M:%S') %>]</small></h4>
    <p><%= comment.body %></p>
  </div>
</li>

app/views/comments/_comments.html.erb
<li class="media comment">
  <%= link_to image_tag(comment.user.avatar_url, alt: comment.user.name, class: "media-object"),
              comment.user.profile_url, target: '_blank', class: 'pull-left' %>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to comment.user.name, comment.user.profile_url, target: '_blank' %> says
      <small class="text-muted">[at <%= comment.created_at.strftime('%-d %B %Y, %H:%M:%S') %>]</small></h4>
    <p><%= comment.body %></p>
  </div>
</li>

app/views/comments/_form.html.erb
<div class="well">
  <%= form_for @comment, remote: true do |f| %>
  	<div class="form-group">
  	  <%= f.label :body, 'Enter your comment: ' %>
  	  <%= f.text_area :body, rows: 3, class: 'form-control', required: true, maxlength: 2000 %>
  	  <small class="label label-warning">Cannot be blank or contain more than 2000 symbols.</small>
  	</div>

  	<%= f.submit 'Post', class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/comments/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome to our mini-chat!</h1>
  <p class="lead">Please sign in</p>
  <%= link_to 'T','/auth/twitter', class: 'social twitter' %>
  <%= link_to 'F','/auth/facebook', class: 'social facebook' %>
</div>

app/views/comments/create.js.erb
publisher = client.publish('/comments', {
  message: '<%= j render @comment %>'
});

publisher.callback(function() {
  $('#comment_body').val('');
  $('#new_comment').find("input[type='submit']").val('Submit').prop('disabled', false)
});

publisher.errback(function() {
  alert('There was an error while posting your comment.');
});

app/views/comments/index.js.erb
$('#comments').find('.media-list').html('<%= j render @ comments %>');
Poller.Poll();

app/views/comments/new.html.erb
<% if current_user %>
  <div class="page-header">
  	<h1>Join the discussion</h1>
  </div>

  <%= render 'form' %>
  <div class = "panel panel-default" id="comments">
  	<div class="panel-body">
  		<ul class="media-list">
  			<%= render @comments %>
  		</ul>
  	</div>
  </div>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta http-equiv="refresh" content="15" />
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
  	<div class="container">
  	  <div class="navbar-header">
  	  	<%= link_to 'Mini-chat', root_path, class: 'navbar-brand' %>
  	  </div>

  	  <% if current_user%>
  	  	<ul  class="nav navbar-nav navbar-right">
  	  	  <li><%= image_tag current_user.avatar_url %></li>
  	  	  <li><%= link_to 'Sign Out', sign_out_path %></li>
  	  	</ul>
  	  <% end %>

  	</div>
  </div>

  <div class="container">
  	<% flash.each do |key, value| %>
  	  <div class="alert-alert-<%= key %>">
  	  	<%= value %>
  	  </div>
  	<% end %>
  	<%= yield %>
  </div>

</body>
</html>